- name: Setup Operating system
  hosts: new_setup
  gather_facts: true
  become: true

  tasks:

    - name: Install packages, set up directories, copy files
      tags: apt
      block:
        - include_role:
            name: files_and_directories

    - name: Synchronoize over config files
      tags: sync
      block:
        - include_role:
            name: sync_conf

    - name: Install Configure Neovim
      tags: neovim
      vars:
        lua_version: 5.4.4
        luarocks_version: 3.9.2
        neovim_version: "latest"
      block:
        - include_role:
            name: neovim

    - name: build stuff
      tags: build
      vars:
        npm_packages:
          - bash-language-server
          - neovim
        node_version: "18.7.0"
        python_version: "3.9.5"
        pyenv_install_dir: "/root/pyenv"
        install_python_dir: "{{ pyenv_install_dir }}/versions"
        tmux_env: source123
        python_packages:
          - ansible
          - ansible-lint
          - pynvim
      block:
        -  include_role:
             name: build_stuff

    - name: configure settings in files
      tags: gnu
      block:
        - include_role:
            name: gnu_conf


    - name: Setup pipewire
      tags: pipewire
      vars: 
        disable_pulseaudio: false
        tmux_env: source123
      block:
        - include_role:
            name: pipewire


    - name: configure Firefox
      tags: firefox
      vars:
        local_user: john 
        remote_user: setup  
      block:
        - include_role:
            name: firefox

    - name: Setup rustdesk
      become: yes
      tags: rustdesk
      vars: 
        ansible_user: setup
      block:
        - include_role:
            name: rustdesk 




